options:
  auto-update: true
  autosave-interval: 5
  quest-check-delay: 60
  language: en_us
  text-wrap: 32
party:
  max-members: 4
  enabled: true
  auto-kick: 5
book:
  on-first-join: true
dialogue:
  prefix: '&f'
data:
  dialogue:   dialogues/
  extensions: extensions/
  player:     playerdata/
  presets:    presets/
  questing:   quests/
